# Site
title:              'Rob Porter'
bio:                'Digital Naturalist || Co-founder and CIO at Weever Apps'
description:        "Digital Naturalist"
reading_time:       false
words_per_minute:   200
logo:               'assets/img/feather-7.svg'
background:         'assets/img/sunset-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_CA
url:                http://robporter.ca
#url:                http://127.0.0.1:4000/

# Jekyll
permalink:          /:title/
future:             false
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:              rob@inpictures.ca
twitter:            rgeraldporter
#facebook:           username
github:             rgeraldporter
stackoverflow:      325674/rob-porter
linkedin:           rgeraldporter
#xing:              username
instagram:          rgeraldporter
medium:             '@rgeraldporter'
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            rgeraldporter
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
